# permissions for end users to edit cuebuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kustomization-editor-role
rules:
- apiGroups:
  - cuebuild.toolkit.fluxcd.io
  resources:
  - cuebuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cuebuild.toolkit.fluxcd.io
  resources:
  - cuebuilds/status
  verbs:
  - get
