# permissions for end users to edit cueexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cueexport-editor-role
rules:
- apiGroups:
  - cue.toolkit.fluxcd.io
  resources:
  - cueexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cue.toolkit.fluxcd.io
  resources:
  - cueexports/status
  verbs:
  - get
