# permissions for end users to view cueexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cueexport-viewer-role
rules:
- apiGroups:
  - cue.toolkit.fluxcd.io
  resources:
  - cueexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cue.toolkit.fluxcd.io
  resources:
  - cueexports/status
  verbs:
  - get
