apiVersion: cuebuild.toolkit.fluxcd.io/v1beta1
kind: CueBuild
metadata:
  name: webapp-dev
spec:
  interval: 5m
  path: "./deploy/..."
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp-latest
  validation: client
  healthChecks:
    - kind: Deployment
      name: backend
      namespace: webapp
    - kind: Deployment
      name: frontend
      namespace: webapp
  timeout: 2m
---
apiVersion: cuebuild.toolkit.fluxcd.io/v1beta1
kind: CueBuild
metadata:
  name: webapp-production
spec:
  interval: 15m
  path: "./deploy/overlays/production/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp-releases
  validation: client
  healthChecks:
    - kind: Deployment
      name: backend
      namespace: production
    - kind: Deployment
      name: frontend
      namespace: production
  timeout: 2m
