apiVersion: cuebuild.toolkit.fluxcd.io/v1alpha1
kind: CueBuild
metadata:
  name: addreas-homelab
spec:
  interval: 5m
  packages:
  - ./resources/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: addreas-homelab
  validation: client
  healthChecks:
    - kind: StatefulSet
      name: bitwarden
      namespace: default
    - kind: StatefulSet
      name: unifi-controller
      namespace: default
  timeout: 2m
